@baseUrl = http://localhost:8888/api/v1

### ! get all tasks
GET {{baseUrl}}/tasks

### ! get a task
GET {{baseUrl}}/tasks/dc15f411-3770-420c-9d4e-1f670524ae48

### ! get a task - 404
GET {{baseUrl}}/tasks/error

### ! create a task
POST {{baseUrl}}/tasks
Content-Type: application/json

{
  "title": "New Task",
  "description": "Description for New Task",
  "userId" : "fcea2b64-2dba-47d1-ac32-cdc13541efeb",
}

### ! update a task
PUT {{baseUrl}}/tasks/dc15f411-3770-420c-9d4e-1f670524ae48
Content-Type: application/json

{
  "title": "Updated Task",
  "description": "Description for Updated Task",
  "completed": true
}

### ! patch a task
PATCH {{baseUrl}}/tasks/dc15f411-3770-420c-9d4e-1f670524ae48
Content-Type: application/json

{
  "completed": false
}

### ! delete a task
DELETE {{baseUrl}}/tasks/dc15f411-3770-420c-9d4e-1f670524ae48

### ! delete a task - 404
DELETE {{baseUrl}}/tasks/error